In [1]:
# import librires
import pandas as pd

### Data Understanding

In [2]:
#Read csv file
df= pd.read_csv("cleaning_challenge.csv")

In [3]:
#Display first 5 rows
df.head()

,Invoice_ID,City,Course_Type,Price,Discount,Final_Total,Enrollment_Date,Rating,Course_Details
0,INV-10001,Mecca,Recorded Subscription,532,266,266,2023-03-17,4.1,Laravel & PHP | Advanced
1,INV-10002,Jeddah,Recorded Subscription,289,0,289,"2023, March 15",4.5,Laravel & PHP | Beginner
2,INV-10003,Dammam,Recorded Subscription,474,94,380,"2023, March 15",4.4,UI/UX Design | Intermediate
3,INV-10004,Khobar,Recorded Subscription,265,0,265,"2023, March 15",4.7,UI/UX Design | Beginner
4,INV-10005,Mecca,Recorded Subscription,228,45,183,22-03-2023,4.6,React & Next.js | Beginner

In [4]:
# Display last 5 rows
df.tail()

,Invoice_ID,City,Course_Type,Price,Discount,Final_Total,Enrollment_Date,Rating,Course_Details
4997,INV-14998,Mecca,Recorded Subscription,244,48,196,30-04-2023,4.1,React & Next.js | Beginner
4998,INV-14999,Mecca,Live Bootcamp,1559,0,1559,"2023, March 15",4.7,Laravel & PHP | Beginner
4999,INV-15000,Medina,Recorded Subscription,280,140,140,2023-07-17,4.7,Python Basics | Beginner
5000,INV-10006,Riyadh,lIVE bOOTCAMP,1542,0,1542,2023-03-12,4.5,Flutter Development | Beginner
5001,INV-10007,Khobar,rECORDED sUBSCRIPTION,269,134,135,10-02-2023,4.5,Flutter Development | Beginner

In [5]:
# Display random data 
df.sample(5)

,Invoice_ID,City,Course_Type,Price,Discount,Final_Total,Enrollment_Date,Rating,Course_Details
4520,INV-14521,Medina,Recorded Subscription,271,135,136,"2023, March 15",4.1,Flutter Development | Beginner
4493,INV-14494,Khobar,Recorded Subscription,210,0,210,"2023, March 15",4.5,UI/UX Design | Beginner
1491,INV-11492,Riyadh,Live Bootcamp,2120,0,2120,25-01-2023,4.7,Flutter Development | Intermediate
1282,INV-11283,Tabuk,Recorded Subscription,286,143,143,"2023, March 15",4.5,Flutter Development | Beginner
3975,INV-13976,Khobar,Recorded Subscription,225,45,180,2023-05-12,4.3,Python Basics | Beginner

In [6]:
# Number of Rows , Column
df.shape

(5002, 9)

In [7]:
#understand the type of data and see if there is a lost data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5002 entries, 0 to 5001
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Invoice_ID       5002 non-null   object
 1   City             5002 non-null   object
 2   Course_Type      5002 non-null   object
 3   Price            5002 non-null   int64
 4   Discount         5002 non-null   int64
 5   Final_Total      5002 non-null   int64
 6   Enrollment_Date  5002 non-null   object
 7   Rating           4952 non-null   object
 8   Course_Details   5002 non-null   object
dtypes: int64(3), object(6)
memory usage: 351.8+ KB

In [8]:
#inspect about the numaric columns
df.describe()

             Price     Discount  Final_Total
count  5002.000000  5002.000000  5002.000000
mean    716.730708    60.266094   656.464614
std     718.706955    76.638282   736.086976
min     200.000000     0.000000   100.000000
25%     293.000000     0.000000   231.000000
50%     404.500000    43.000000   323.000000
75%     599.750000    98.000000   528.750000
max    2999.000000   325.000000  2999.000000

In [9]:
# calculate the overall Course_Type values
course_type_counts = df["Course_Type"].value_counts()
course_type_counts

Course_Type
Recorded Subscription    4020
Live Bootcamp             980
lIVE bOOTCAMP               1
rECORDED sUBSCRIPTION       1
Name: count, dtype: int64

In [10]:
# Get the top 5 cities with the most courses
df.groupby("City")["Invoice_ID"].count().sort_values(ascending=False).head(5)

City
Riyadh    938
Jeddah    860
Dammam    775
Medina    634
Khobar    627
Name: Invoice_ID, dtype: int64

In [11]:
# Calculate the average price for each type 
df.groupby("Course_Type")["Price"].mean()

Course_Type
Live Bootcamp            2106.415306
Recorded Subscription     377.857960
lIVE bOOTCAMP            1542.000000
rECORDED sUBSCRIPTION     269.000000
Name: Price, dtype: float64

### Data cleaning 🧹

In [12]:
#Creating a copy
clean_df= df.copy()

In [13]:
#standrize  the Course_Type column(lower letter)
clean_df["Course_Type"]= clean_df["Course_Type"].str.lower()

In [14]:
#check
clean_df.head()

,Invoice_ID,City,Course_Type,Price,Discount,Final_Total,Enrollment_Date,Rating,Course_Details
0,INV-10001,Mecca,recorded subscription,532,266,266,2023-03-17,4.1,Laravel & PHP | Advanced
1,INV-10002,Jeddah,recorded subscription,289,0,289,"2023, March 15",4.5,Laravel & PHP | Beginner
2,INV-10003,Dammam,recorded subscription,474,94,380,"2023, March 15",4.4,UI/UX Design | Intermediate
3,INV-10004,Khobar,recorded subscription,265,0,265,"2023, March 15",4.7,UI/UX Design | Beginner
4,INV-10005,Mecca,recorded subscription,228,45,183,22-03-2023,4.6,React & Next.js | Beginner

In [15]:
# check if there is any duplicates rows
clean_df.duplicated().sum()

np.int64(1)

In [16]:
# drop duplicate rows
clean_df.drop_duplicates(inplace = True)

In [17]:
#check again to make sure duplicates are gone
clean_df.duplicated().sum()

np.int64(0)

In [18]:
#Checking missing values
clean_df.isnull().sum()

Invoice_ID          0
City                0
Course_Type         0
Price               0
Discount            0
Final_Total         0
Enrollment_Date     0
Rating             50
Course_Details      0
dtype: int64

In [19]:
# Convert 'Rating' to numeric, forcing non-numeric values to NaN
clean_df['Rating'] = pd.to_numeric(clean_df['Rating'], errors='coerce')

In [20]:
# Check the info again to see if it changed to float64
print(clean_df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 5001 entries, 0 to 5000
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Invoice_ID       5001 non-null   object
 1   City             5001 non-null   object
 2   Course_Type      5001 non-null   object
 3   Price            5001 non-null   int64
 4   Discount         5001 non-null   int64
 5   Final_Total      5001 non-null   int64
 6   Enrollment_Date  5001 non-null   object
 7   Rating           4950 non-null   float64
 8   Course_Details   5001 non-null   object
dtypes: float64(1), int64(3), object(5)
memory usage: 390.7+ KB
None

In [21]:
#Fill missing values in 'Rating' with the mean to preserve data size
mean_rating= clean_df["Rating"].mean()
clean_df["Rating"] = clean_df["Rating"].fillna(mean_rating)

In [22]:
# Verify no more missing values
print(clean_df['Rating'].isnull().sum())

0

In [23]:
# 4) check
clean_df.head(10)

,Invoice_ID,City,Course_Type,Price,Discount,Final_Total,Enrollment_Date,Rating,Course_Details
0,INV-10001,Mecca,recorded subscription,532,266,266,2023-03-17,4.100000,Laravel & PHP | Advanced
1,INV-10002,Jeddah,recorded subscription,289,0,289,"2023, March 15",4.500000,Laravel & PHP | Beginner
2,INV-10003,Dammam,recorded subscription,474,94,380,"2023, March 15",4.400000,UI/UX Design | Intermediate
3,INV-10004,Khobar,recorded subscription,265,0,265,"2023, March 15",4.700000,UI/UX Design | Beginner
4,INV-10005,Mecca,recorded subscription,228,45,183,22-03-2023,4.600000,React & Next.js | Beginner
5,INV-10006,Riyadh,live bootcamp,1542,0,1542,1900-01-01,4.500000,Flutter Development | Beginner
6,INV-10007,Khobar,recorded subscription,269,134,135,10-02-2023,4.500000,Flutter Development | Beginner
7,INV-10008,Tabuk,recorded subscription,211,42,169,"2023, March 15",4.700000,Data Analysis | Beginner
8,INV-10009,Riyadh,recorded subscription,397,0,397,"2023, March 15",4.381051,Flutter Development | Intermediate
9,INV-10010,Jeddah,recorded subscription,292,0,292,08-03-2023,4.600000,Python Basics | Beginner

In [24]:

# 1) Clean mixed date formats using format='mixed'
clean_df["Enrollment_Date"] = pd.to_datetime(
    clean_df["Enrollment_Date"],
    format="mixed",
    errors="coerce"
)

#2) Remove invalid dates such as 1900-01-01
clean_df = clean_df[clean_df["Enrollment_Date"] != pd.Timestamp("1900-01-01")]

# 3) Reset the index after deletion
clean_df = clean_df.reset_index(drop=True)

# 4) check
clean_df.head(10)

,Invoice_ID,City,Course_Type,Price,Discount,Final_Total,Enrollment_Date,Rating,Course_Details
0,INV-10001,Mecca,recorded subscription,532,266,266,2023-03-17,4.100000,Laravel & PHP | Advanced
1,INV-10002,Jeddah,recorded subscription,289,0,289,2023-03-15,4.500000,Laravel & PHP | Beginner
2,INV-10003,Dammam,recorded subscription,474,94,380,2023-03-15,4.400000,UI/UX Design | Intermediate
3,INV-10004,Khobar,recorded subscription,265,0,265,2023-03-15,4.700000,UI/UX Design | Beginner
4,INV-10005,Mecca,recorded subscription,228,45,183,2023-03-22,4.600000,React & Next.js | Beginner
5,INV-10007,Khobar,recorded subscription,269,134,135,2023-10-02,4.500000,Flutter Development | Beginner
6,INV-10008,Tabuk,recorded subscription,211,42,169,2023-03-15,4.700000,Data Analysis | Beginner
7,INV-10009,Riyadh,recorded subscription,397,0,397,2023-03-15,4.381051,Flutter Development | Intermediate
8,INV-10010,Jeddah,recorded subscription,292,0,292,2023-08-03,4.600000,Python Basics | Beginner
9,INV-10011,Jeddah,recorded subscription,210,105,105,2023-12-13,4.100000,Python Basics | Beginner

In [25]:
#check
clean_df.head(10)

,Invoice_ID,City,Course_Type,Price,Discount,Final_Total,Enrollment_Date,Rating,Course_Details
0,INV-10001,Mecca,recorded subscription,532,266,266,2023-03-17,4.100000,Laravel & PHP | Advanced
1,INV-10002,Jeddah,recorded subscription,289,0,289,2023-03-15,4.500000,Laravel & PHP | Beginner
2,INV-10003,Dammam,recorded subscription,474,94,380,2023-03-15,4.400000,UI/UX Design | Intermediate
3,INV-10004,Khobar,recorded subscription,265,0,265,2023-03-15,4.700000,UI/UX Design | Beginner
4,INV-10005,Mecca,recorded subscription,228,45,183,2023-03-22,4.600000,React & Next.js | Beginner
5,INV-10007,Khobar,recorded subscription,269,134,135,2023-10-02,4.500000,Flutter Development | Beginner
6,INV-10008,Tabuk,recorded subscription,211,42,169,2023-03-15,4.700000,Data Analysis | Beginner
7,INV-10009,Riyadh,recorded subscription,397,0,397,2023-03-15,4.381051,Flutter Development | Intermediate
8,INV-10010,Jeddah,recorded subscription,292,0,292,2023-08-03,4.600000,Python Basics | Beginner
9,INV-10011,Jeddah,recorded subscription,210,105,105,2023-12-13,4.100000,Python Basics | Beginner

### Data Processing 👩🏻‍💻

In [26]:
# split Course_Details column and fix length issues
clean_df[["Course_Name", "Level"]] = clean_df["Course_Details"].str.split("|", n=1, expand=True)

In [27]:
#check
clean_df.head(10)

,Invoice_ID,City,Course_Type,Price,Discount,Final_Total,Enrollment_Date,Rating,Course_Details,Course_Name,Level
0,INV-10001,Mecca,recorded subscription,532,266,266,2023-03-17,4.100000,Laravel & PHP | Advanced,Laravel & PHP,Advanced
1,INV-10002,Jeddah,recorded subscription,289,0,289,2023-03-15,4.500000,Laravel & PHP | Beginner,Laravel & PHP,Beginner
2,INV-10003,Dammam,recorded subscription,474,94,380,2023-03-15,4.400000,UI/UX Design | Intermediate,UI/UX Design,Intermediate
3,INV-10004,Khobar,recorded subscription,265,0,265,2023-03-15,4.700000,UI/UX Design | Beginner,UI/UX Design,Beginner
4,INV-10005,Mecca,recorded subscription,228,45,183,2023-03-22,4.600000,React & Next.js | Beginner,React & Next.js,Beginner
5,INV-10007,Khobar,recorded subscription,269,134,135,2023-10-02,4.500000,Flutter Development | Beginner,Flutter Development,Beginner
6,INV-10008,Tabuk,recorded subscription,211,42,169,2023-03-15,4.700000,Data Analysis | Beginner,Data Analysis,Beginner
7,INV-10009,Riyadh,recorded subscription,397,0,397,2023-03-15,4.381051,Flutter Development | Intermediate,Flutter Development,Intermediate
8,INV-10010,Jeddah,recorded subscription,292,0,292,2023-08-03,4.600000,Python Basics | Beginner,Python Basics,Beginner
9,INV-10011,Jeddah,recorded subscription,210,105,105,2023-12-13,4.100000,Python Basics | Beginner,Python Basics,Beginner